-- MySQL Script generated by MySQL Workbench
-- Mi 24 Feb 2021 19:43:57 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Tasks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Tasks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Tasks` ;
USE `Tasks` ;

-- -----------------------------------------------------
-- Table `Tasks`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `Tasks`.`Tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tasks`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `Tasks`.`Tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tasks`.`Subtasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks`.`Subtasks` ;

CREATE TABLE IF NOT EXISTS `Tasks`.`Subtasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Points` INT NOT NULL,
  `Tasks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Tasks_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Subtasks_Tasks_idx` (`Tasks_id` ASC) VISIBLE,
  CONSTRAINT `fk_Subtasks_Tasks`
    FOREIGN KEY (`Tasks_id`)
    REFERENCES `Tasks`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tasks`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks`.`Users` ;

CREATE TABLE IF NOT EXISTS `Tasks`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tasks`.`Tasks_has_Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks`.`Tasks_has_Users` ;

CREATE TABLE IF NOT EXISTS `Tasks`.`Tasks_has_Users` (
  `Tasks_id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`Tasks_id`, `Users_id`),
  INDEX `fk_Tasks_has_Users_Users1_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Tasks_has_Users_Tasks1_idx` (`Tasks_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tasks_has_Users_Tasks1`
    FOREIGN KEY (`Tasks_id`)
    REFERENCES `Tasks`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tasks_has_Users_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Tasks`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tasks`.`Submissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks`.`Submissions` ;

CREATE TABLE IF NOT EXISTS `Tasks`.`Submissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Users_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Submissions_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Submissions_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Tasks`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tasks`.`Result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tasks`.`Result` ;

CREATE TABLE IF NOT EXISTS `Tasks`.`Result` (
  `Subtasks_id` INT NOT NULL,
  `Subtasks_Tasks_id` INT NOT NULL,
  `Submissions_id` INT NOT NULL,
  `Submissions_Users_id` INT NOT NULL,
  `Points` INT NULL,
  `Code` VARCHAR(45) NULL,
  PRIMARY KEY (`Subtasks_id`, `Subtasks_Tasks_id`, `Submissions_id`, `Submissions_Users_id`),
  INDEX `fk_Subtasks_has_Submissions_Submissions1_idx` (`Submissions_id` ASC, `Submissions_Users_id` ASC) VISIBLE,
  INDEX `fk_Subtasks_has_Submissions_Subtasks1_idx` (`Subtasks_id` ASC, `Subtasks_Tasks_id` ASC) VISIBLE,
  CONSTRAINT `fk_Subtasks_has_Submissions_Subtasks1`
    FOREIGN KEY (`Subtasks_id` , `Subtasks_Tasks_id`)
    REFERENCES `Tasks`.`Subtasks` (`id` , `Tasks_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subtasks_has_Submissions_Submissions1`
    FOREIGN KEY (`Submissions_id` , `Submissions_Users_id`)
    REFERENCES `Tasks`.`Submissions` (`id` , `Users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
