dbname : ""
dbuser : ""
dbpassword : ""
port : "8080"
dataDir : ""
cert : "cert/public.crt"
key : "cert/private.key"

containerConfig : 
  numContainer : 2
  languages : 
    - name : "C"
      abbreviation : "c"
      preLaunchTask : "gcc -O2 main.c"
      launchTask : "./a.out"
    - name : "C++"
      abbreviation : "cpp"
      preLaunchTask : "g++ -O2 main.cpp"
      launchTask : "./a.out"
    - name : "Golang"
      abbreviation : "go"
      preLaunchTask : "go build main.go"
      launchTask : "./main"
    - name : "Javascript"
      abbreviation : "js"
      preLaunchTask : ""
      launchTask : "node main.js"
    - name : "Typescript"
      abbreviation : "ts"
      preLaunchTask : ""
      launchTask : "ts-node main.ts"
    - name : "Python"
      abbreviation : "py"
      preLaunchTask : ""
      launchTask : "python3 main.py"
    - name : "Java"
      abbreviation : "java"
      preLaunchTask : "javac main.java"
      launchTask : "java main"
    - name : "Haskell"
      abbreviation : "hs"
      preLaunchTask : "ghc --make main"
      launchTask : "./main"
  